### ISSUE TITLE
Intellisense Code Completion

### ISSUE THREAD

**Issue by dresch86** [mesonbuild/vscode-meson#12] opened 2019-11-12 02:12 UTC
Just curious....does this plugin feed the include directories for headers into VSCode for code completion? I've got a bunch of red squiggles because VSCode can't find the headers. I had Ninja keep the .rsp files, and supposedly support for them was added in the latest version of the cpptools plugin. Everything compiles fine and runs as expected so Ninja and Clang in MSYS2 are doing their job.

**Comment by Ongy** [comment] 2022-02-11 16:09
Do you still have this issue? I don't have a windows seutp, but works fine for me on linux with the current code.

**Comment by dcbaker** [comment] 2022-11-28 20:10
I'm going to close it, if it's still valid we'll re-open it.

**Closed by dcbaker** 2022-11-28 20:10 UTC
Labels: enhancement, question

**Comment by bluca** [comment] 2024-07-26 14:00
This is still an issue for me, as soon as I enable this extension, intellisense breaks completely.

**Comment by Hi-Angel** [comment] 2024-07-26 14:04
@bluca I think it would be more productive to create a new issue, because this one never even had steps to reproduce.

**Comment by bluca** [comment] 2024-07-26 14:09
--> https://github.com/mesonbuild/vscode-meson/issues/254
